# Generated by Django 2.1.5 on 2019-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
